-- Ejecutar en Supabase SQL Editor.
-- Tabla para guardar los análisis del supervisor de conversaciones.

create table if not exists public.conversation_supervision_reports (
  id bigint generated by default as identity primary key,
  analyzed_at timestamptz not null default now(),

  chatwoot_account_id integer not null,
  conversation_id bigint not null unique,
  conversation_url text not null,

  inbox_id integer,
  inbox_name text,
  branch_name text,
  channel_name text,
  status text,

  contact_id bigint,
  contact_name text,
  contact_phone text,
  contact_email text,
  assignee_name text,

  stage text not null default 'indefinida',
  risk_level text not null default 'medio',
  score_general integer check (score_general is null or (score_general >= 0 and score_general <= 100)),
  customer_sentiment text,

  alerts jsonb not null default '[]'::jsonb,
  strengths jsonb not null default '[]'::jsonb,
  improvement_opportunities jsonb not null default '[]'::jsonb,
  differentiators_detected jsonb not null default '[]'::jsonb,

  missed_followups boolean not null default false,
  abandoned_chat boolean not null default false,
  requires_human_review boolean not null default false,

  summary text,
  recommendation text,

  ai_agent_present boolean not null default false,
  ai_agent_score integer check (ai_agent_score is null or (ai_agent_score >= 0 and ai_agent_score <= 100)),
  ai_agent_summary text,
  ai_agent_strengths jsonb not null default '[]'::jsonb,
  ai_agent_issues jsonb not null default '[]'::jsonb,
  ai_agent_recommendation text,

  architect_present boolean not null default false,
  architect_names jsonb not null default '[]'::jsonb,
  architect_score integer check (architect_score is null or (architect_score >= 0 and architect_score <= 100)),
  architect_summary text,
  architect_strengths jsonb not null default '[]'::jsonb,
  architect_issues jsonb not null default '[]'::jsonb,
  architect_recommendation text,

  handoff_quality text not null default 'no_aplica',
  handoff_summary text,
  ai_agent_outbound_count integer not null default 0,
  architect_outbound_count integer not null default 0,

  metrics jsonb not null default '{}'::jsonb,
  raw_analysis jsonb not null default '{}'::jsonb,
  ai_model text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Migración para tablas existentes creadas antes de separar AI Agent vs arquitecto.
alter table public.conversation_supervision_reports
  add column if not exists ai_agent_present boolean not null default false,
  add column if not exists ai_agent_score integer,
  add column if not exists ai_agent_summary text,
  add column if not exists ai_agent_strengths jsonb not null default '[]'::jsonb,
  add column if not exists ai_agent_issues jsonb not null default '[]'::jsonb,
  add column if not exists ai_agent_recommendation text,
  add column if not exists architect_present boolean not null default false,
  add column if not exists architect_names jsonb not null default '[]'::jsonb,
  add column if not exists architect_score integer,
  add column if not exists architect_summary text,
  add column if not exists architect_strengths jsonb not null default '[]'::jsonb,
  add column if not exists architect_issues jsonb not null default '[]'::jsonb,
  add column if not exists architect_recommendation text,
  add column if not exists handoff_quality text not null default 'no_aplica',
  add column if not exists handoff_summary text,
  add column if not exists ai_agent_outbound_count integer not null default 0,
  add column if not exists architect_outbound_count integer not null default 0;

create index if not exists idx_supervision_reports_analyzed_at
  on public.conversation_supervision_reports (analyzed_at desc);

create index if not exists idx_supervision_reports_branch
  on public.conversation_supervision_reports (branch_name);

create index if not exists idx_supervision_reports_inbox
  on public.conversation_supervision_reports (inbox_id);

create index if not exists idx_supervision_reports_stage
  on public.conversation_supervision_reports (stage);

create index if not exists idx_supervision_reports_risk
  on public.conversation_supervision_reports (risk_level);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_supervision_reports_updated_at
  on public.conversation_supervision_reports;

create trigger trg_supervision_reports_updated_at
before update on public.conversation_supervision_reports
for each row
execute function public.set_updated_at();

-- Recomendado: mantener RLS activo y consultar esta tabla solo desde el backend con service role.
alter table public.conversation_supervision_reports enable row level security;

-- Snapshots diarios para seguimiento comercial (diff día a día vs Chatwoot).
create table if not exists public.conversation_followup_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  captured_at timestamptz not null default now(),

  chatwoot_account_id integer not null,
  conversation_id bigint not null,
  conversation_url text,

  inbox_id integer,
  branch_name text,
  contact_id bigint,
  contact_name text,
  contact_phone text,

  stage text not null default 'indefinida',
  risk_level text,

  message_count integer not null default 0,
  inbound_count integer not null default 0,
  outbound_count integer not null default 0,
  human_outbound_count integer not null default 0,
  human_outbound_today boolean not null default false,

  last_message_at timestamptz,
  last_outbound_at timestamptz,
  last_inbound_at timestamptz,
  last_human_outbound_at timestamptz,
  last_outbound_sender_group text,

  metrics jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  unique (conversation_id, snapshot_date)
);

create index if not exists idx_followup_snapshots_date
  on public.conversation_followup_snapshots (snapshot_date desc);

create index if not exists idx_followup_snapshots_conversation
  on public.conversation_followup_snapshots (conversation_id, snapshot_date desc);

create index if not exists idx_followup_snapshots_branch
  on public.conversation_followup_snapshots (branch_name, snapshot_date desc);

create index if not exists idx_followup_snapshots_stage
  on public.conversation_followup_snapshots (stage, snapshot_date desc);

alter table public.conversation_followup_snapshots enable row level security;
